# See: https://dart.dev/tools/pub/pubspec
name: model_viewer_plus
version: 1.1.5
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
homepage: https://github.com/omchiii/model_viewer_plus.dart
repository: https://github.com/omchiii/model_viewer_plus.dart
issue_tracker: https://github.com/omchiii/model_viewer_plus.dart/issues
platforms:
  android:
  ios:
  web:
dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^3.1.1
  webview_flutter: ^3.0.1
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  assets:
    - etc/assets/template.html
    - etc/assets/model-viewer.js
    - etc/assets/variant-list.js
    - etc/assets/external-list.js
    - etc/assets/panningScript.js
    - etc/assets/model-manipulation.js
